/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import komunikacija.KomunikacijaSaServerom;
import konstante.Operacije;
import niti.CekajOdgovorOdServeraStalnoUvekIUvek;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miroslav
 */
public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        boolean povezan = KomunikacijaSaServerom.getInstance().poveziSe();
        if(povezan){
            labelaStatus.setText("Klijent je povezan sa serverom");
        }else{
            labelaStatus.setText("Klijent nije povezan sa serverom");
            btnObrisi.setEnabled(false);
        }
        
        CekajOdgovorOdServeraStalnoUvekIUvek c = new CekajOdgovorOdServeraStalnoUvekIUvek(this);
        c.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelaBrojevi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelaUkupno = new javax.swing.JLabel();
        labelaIgra = new javax.swing.JLabel();
        labelaStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Brojevi koje je korisnik izbrisao");

        jLabel3.setText("Ukupno izbrisanih brojeva");

        labelaIgra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelaIgra.setText("IGRA JE U TOKU");

        labelaStatus.setText("Klijent je povezan sa serverom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaBrojevi)
                            .addComponent(labelaUkupno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelaIgra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaStatus)
                            .addComponent(btnObrisi))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelaStatus)
                .addGap(12, 12, 12)
                .addComponent(btnObrisi)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelaBrojevi))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelaUkupno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(labelaIgra)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.OBRISI);
        
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
        
        //ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
        
        
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelaBrojevi;
    private javax.swing.JLabel labelaIgra;
    private javax.swing.JLabel labelaStatus;
    private javax.swing.JLabel labelaUkupno;
    // End of variables declaration//GEN-END:variables

    public void srediFormuPosleOdgovora(ServerskiOdgovor so) {
        if(so.isKraj()){
            labelaIgra.setText(so.getPoruka());
            String brojevi = labelaBrojevi.getText();
            brojevi += so.getIzbrisaniBroj()+" ";
            labelaBrojevi.setText(brojevi);
            labelaUkupno.setText(so.getUkupno()+"");
            btnObrisi.setEnabled(false);
        }else{
            String brojevi = labelaBrojevi.getText();
            brojevi += so.getIzbrisaniBroj()+" ";
            labelaBrojevi.setText(brojevi);
            labelaUkupno.setText(so.getUkupno()+"");
        }
    }
}
