/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.PoslovniPartner;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import komponente.model.PoslovniPartnerTableModel;
import kontroler.Kontroler;

/**
 *
 * @author student
 */
public class FPretragaPoslovniPartner extends javax.swing.JDialog {

    /**
     * Creates new form FPretragaPoslovniPartner
     */
    public FPretragaPoslovniPartner(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPoslovniPartner = new javax.swing.JTable();
        jbtnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz poslovnih partnera");

        tblPoslovniPartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pib", "maticni broj", "naziv", "adresa", "mesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPoslovniPartner);

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDetalji)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnDetalji)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        int red = tblPoslovniPartner.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(null, "Izaberi partnera");
        } else {
            JDialog fpartner;
            try {
                fpartner = new FPoslovniPartner(null, true, new PoslovniPartner());
                fpartner.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(FPretragaPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jbtnDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JTable tblPoslovniPartner;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        List<PoslovniPartner> partneri;
        try {
            partneri = Kontroler.vratiPartnere();
            TableModel pptm = new PoslovniPartnerTableModel(partneri);
            tblPoslovniPartner.setModel(pptm);
        } catch (SQLException ex) {
            Logger.getLogger(FPretragaPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FPretragaPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        TableModel tm= tblPoslovniPartner.getModel();
        DefaultTableModel dtm =(DefaultTableModel)tm;
        Object[] red;
        for (PoslovniPartner poslovniPartner : partneri) {
            red= new Object[5];
            red[0]= poslovniPartner.getPib();
            red[1]= poslovniPartner.getMaticniBroj();
            red[2]= poslovniPartner.getNaziv();
            red[3]= poslovniPartner.getUlica() + " " + poslovniPartner.getBroj();
            red[4]= poslovniPartner.getMesto();
            dtm.addRow(red);
        }*/

    }
}
