package forme;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.ModelTabele;
import niti.NitSat;
import server.PokretanjeServeraKlasa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miroslav
 */
public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        srediPocetnuFormu();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaPokrenut = new javax.swing.JLabel();
        btnPokretanjeServera = new javax.swing.JButton();
        labelaSat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaServer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelaPokrenut.setText("jLabel1");

        btnPokretanjeServera.setText("Pokreni server");
        btnPokretanjeServera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokretanjeServeraActionPerformed(evt);
            }
        });

        labelaSat.setText("jLabel1");

        tabelaServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelaSat)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelaPokrenut)
                        .addGap(157, 157, 157)
                        .addComponent(btnPokretanjeServera)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaPokrenut)
                    .addComponent(btnPokretanjeServera))
                .addGap(18, 18, 18)
                .addComponent(labelaSat)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokretanjeServeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokretanjeServeraActionPerformed
        PokretanjeServeraKlasa ps = new PokretanjeServeraKlasa(this);
        ps.start();
    }//GEN-LAST:event_btnPokretanjeServeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokretanjeServera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaPokrenut;
    private javax.swing.JLabel labelaSat;
    private javax.swing.JTable tabelaServer;
    // End of variables declaration//GEN-END:variables

    private void srediPocetnuFormu() {
        labelaPokrenut.setText("Server nije pokrenut");
        jScrollPane1.setVisible(false);
        labelaSat.setVisible(false);
    }

    public void srediFormuPoslePokretanja() {
        btnPokretanjeServera.setVisible(false);
        jScrollPane1.setVisible(true);
        labelaSat.setVisible(true);
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        labelaPokrenut.setText("Server je pokrenut:    "+sdf.format(new Date()));
        NitSat ns = new NitSat(labelaSat);
        ns.start();
        
    }

    public void pukloNeValja() {
        labelaPokrenut.setText("Nista ne valja, taj port je zauzet");
        labelaPokrenut.setForeground(Color.red);
    }

    private void srediTabelu() {
        ModelTabele mt = new ModelTabele();
        tabelaServer.setModel(mt);
    }

    public String odradiPosaoKojiTrebas(int pozicija, String korisnickoIme) {
        ModelTabele mt = (ModelTabele) tabelaServer.getModel();
        String poruka = mt.odradiPosaoKojiTrebaS(pozicija,korisnickoIme);
        
        return poruka;
    }
}
