/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domen.Slovo;
import java.awt.Color;
import javax.swing.JOptionPane;
import komunikacija.KomunikacijaSaServerom;
import model.ModelTabele;
import niti.CekajOdgovorOdServera;
import niti.NitOdborojavanje;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Miroslav
 */
public class KlijentskaForma extends javax.swing.JFrame {

    String korisnik;
    
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        srediTabelu();
        CekajOdgovorOdServera cs = new CekajOdgovorOdServera(this);
        cs.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        btnPoveziSe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaKlijent = new javax.swing.JTable();
        labelaImePRvog = new javax.swing.JLabel();
        labelaImeDrugog = new javax.swing.JLabel();
        labelaPoenaPrvi = new javax.swing.JLabel();
        labelaPoenaDrugi = new javax.swing.JLabel();
        labelaTajmer = new javax.swing.JLabel();
        txtSlovo = new javax.swing.JTextField();
        btnPosalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Korisnicko ime");

        btnPoveziSe.setText("Povezi se");
        btnPoveziSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoveziSeActionPerformed(evt);
            }
        });

        tabelaKlijent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaKlijent);

        labelaImePRvog.setText("jLabel2");

        labelaImeDrugog.setText("jLabel3");

        labelaPoenaPrvi.setText("jLabel4");

        labelaPoenaDrugi.setText("jLabel5");

        labelaTajmer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelaTajmer.setText("jLabel2");

        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPoveziSe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaTajmer)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelaImePRvog)
                                    .addComponent(labelaImeDrugog))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelaPoenaDrugi)
                                    .addComponent(labelaPoenaPrvi)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPosalji)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoveziSe))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelaTajmer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelaImePRvog)
                            .addComponent(labelaPoenaPrvi))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelaImeDrugog))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelaPoenaDrugi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPosalji))
                        .addGap(6, 6, 6))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoveziSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoveziSeActionPerformed
        korisnik = txtKorisnickoIme.getText();
        
        if(!korisnik.contains("@") || korisnik.startsWith("@") || korisnik.endsWith("@")){
            JOptionPane.showMessageDialog(this, "Validacija neuspela @");
            return;
        }
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setUsername(korisnik);
        
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnPoveziSeActionPerformed

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        String slovo = txtSlovo.getText().toUpperCase();
        slovo = slovo.substring(0, 1);
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setUsername(korisnik);
        kz.setSlovo(slovo);
        
        KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
    }//GEN-LAST:event_btnPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosalji;
    private javax.swing.JButton btnPoveziSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaImeDrugog;
    private javax.swing.JLabel labelaImePRvog;
    private javax.swing.JLabel labelaPoenaDrugi;
    private javax.swing.JLabel labelaPoenaPrvi;
    private javax.swing.JLabel labelaTajmer;
    private javax.swing.JTable tabelaKlijent;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtSlovo;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabele mt = new ModelTabele();
        tabelaKlijent.setModel(mt);
    }

    public void nijePocelaIGra() {
        JOptionPane.showMessageDialog(this, "IGRA JOS NIJE POCELA, SACEKAJTE DRUGOG KLIJENTA DA SE POVEZE");
    }

    public void zavrsiIGru(ServerskiOdgovor so) {
        int br1 = so.getBrPoenaPrviIgrac();
        int br2 = so.getBrPoenaDrugiIgrac();
        String prvi = so.getPrviIgrac();
        String drugi = so.getDrugiIgrac();
        
        if(br1>=br2){
            labelaImePRvog.setForeground(Color.green);
            labelaPoenaPrvi.setText(br1+"");
            labelaImeDrugog.setForeground(Color.red);
            labelaPoenaDrugi.setText(br2+"");
        }else{
            labelaImePRvog.setForeground(Color.red);
            labelaPoenaPrvi.setText(br1+"");
            labelaImeDrugog.setForeground(Color.green);
            labelaPoenaDrugi.setText(br2+"");
         }
        btnPosalji.setEnabled(false);
        
        JOptionPane.showMessageDialog(null, so.getPoruka());
        
    }

    public void srediFormu(ServerskiOdgovor so) {
        
        int br1 = so.getBrPoenaPrviIgrac();
        int br2 = so.getBrPoenaDrugiIgrac();
        String prvi = so.getPrviIgrac();
        String drugi = so.getDrugiIgrac();
        
        labelaImePRvog.setText(prvi);
        labelaPoenaPrvi.setText(br1+"");
        labelaImeDrugog.setText(drugi);
        labelaPoenaDrugi.setText(br2+"");
        
        Slovo slovo = so.getSlovo();
        if(slovo!=null){
            ModelTabele model = (ModelTabele) tabelaKlijent.getModel();
            model.dodajSlovo(slovo);
        }else{
            int ukupno = so.getUkupnoSekundi();
            NitOdborojavanje no = new NitOdborojavanje(ukupno, this);
            no.start();
        }
        
    }

    public void srediTajmer(int ukupano) {
        labelaTajmer.setText(ukupano+"");
    }
}
