/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Mesto;
import domen.PoslovniPartner;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komponente.model.PoslovniPartnerTableModel;
import request.RequestObject;
import response.ResponseObject;
import util.ActionCode;
import util.EnumResponseStatus;

/**
 *
 * @author student
 */
public class FPoslovniPartner extends javax.swing.JDialog {

    /**
     * Creates new form FPoslovniPartner
     */
    public FPoslovniPartner(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        popuniKomboMesto();
        prikaziSvePartnere();
        srediTabeluZaUnos();
    }

    public FPoslovniPartner(java.awt.Frame parent, boolean modal, PoslovniPartner pp) throws IOException {
        super(parent, modal);
        initComponents();
        setTitle("Detalji o poslovnom partneru");
        popuniKomboMesto();
        prikaziPartnera(pp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPib = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtMaticniBroj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtxtUlica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtBroj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcomboMesto = new javax.swing.JComboBox<>();
        btnDodaj = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnlNoviPartneri = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblNoviPartneri = new javax.swing.JTable();
        jpnlPoslovniPartneri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSviPartneri = new javax.swing.JTable();
        jbtnSacuvajSve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos poslovnog partnera");

        jLabel1.setText("PIB:");

        jLabel2.setText("Maticni broj:");

        jLabel3.setText("Naziv:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sediste firme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setText("Ulica");

        jLabel5.setText("Broj");

        jLabel6.setText("Mesto");

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDodaj)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtBroj, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtUlica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcomboMesto, 0, 150, Short.MAX_VALUE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcomboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnDodaj)
                .addContainerGap())
        );

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.setEnabled(false);
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtblNoviPartneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblNoviPartneri);

        javax.swing.GroupLayout jpnlNoviPartneriLayout = new javax.swing.GroupLayout(jpnlNoviPartneri);
        jpnlNoviPartneri.setLayout(jpnlNoviPartneriLayout);
        jpnlNoviPartneriLayout.setHorizontalGroup(
            jpnlNoviPartneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlNoviPartneriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlNoviPartneriLayout.setVerticalGroup(
            jpnlNoviPartneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlNoviPartneriLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novi partneri", jpnlNoviPartneri);

        jtblSviPartneri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblSviPartneri);

        javax.swing.GroupLayout jpnlPoslovniPartneriLayout = new javax.swing.GroupLayout(jpnlPoslovniPartneri);
        jpnlPoslovniPartneri.setLayout(jpnlPoslovniPartneriLayout);
        jpnlPoslovniPartneriLayout.setHorizontalGroup(
            jpnlPoslovniPartneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPoslovniPartneriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlPoslovniPartneriLayout.setVerticalGroup(
            jpnlPoslovniPartneriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPoslovniPartneriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Poslovni partneri", jpnlPoslovniPartneri);

        jbtnSacuvajSve.setText("Sacuvaj sve");
        jbtnSacuvajSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jtxtNaziv, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtPib))))
                    .addComponent(jbtnSacuvaj))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSacuvajSve))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtPib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnSacuvajSve))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
//        String pib = jtxtPib.getText().trim();
//        String maticniBroj = jtxtMaticniBroj.getText().trim();
//        String naziv = jtxtNaziv.getText().trim();
//        String ulica = jtxtUlica.getText().trim();
//        String broj = jtxtBroj.getText().trim();
//        Mesto mesto = (Mesto) jcomboMesto.getSelectedItem();
//        try {
//            validacija(pib, maticniBroj);
//            PoslovniPartner partner = new PoslovniPartner(pib, maticniBroj, naziv, ulica, broj, mesto);
//            kontroler.Kontroler.unesiPoslovnogPartnera(partner);
//            JOptionPane.showMessageDialog(this, "Partner je sacuvan");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Greska: " + e.getMessage());
//        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        String pib = jtxtPib.getText().trim();
        String maticniBroj = jtxtMaticniBroj.getText().trim();
        String naziv = jtxtNaziv.getText().trim();
        String ulica = jtxtUlica.getText().trim();
        String broj = jtxtBroj.getText().trim();
        Mesto mesto = (Mesto) jcomboMesto.getSelectedItem();
        try {
            validacija(pib, maticniBroj);
            PoslovniPartner partner = new PoslovniPartner(pib, maticniBroj, naziv, ulica, broj, mesto);
            PoslovniPartnerTableModel pptm = (PoslovniPartnerTableModel) jtblNoviPartneri.getModel();
            pptm.dodajNoviRed(partner);
            JOptionPane.showMessageDialog(this, "Partner je sacuvan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greska: " + e.getMessage());
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void jbtnSacuvajSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajSveActionPerformed
        try {
            PoslovniPartnerTableModel pptm = (PoslovniPartnerTableModel) jtblNoviPartneri.getModel();
            List<PoslovniPartner> businessPartners = pptm.vratiPodatke();

            RequestObject request = new RequestObject();
            request.setAction(ActionCode.SAVE_ALL_BUSINESS_PARTNERS);
            request.setRequest(businessPartners);
            
            Socket socket = session.Session.getInstance().getSocket();
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            out.writeObject(request);

            ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
            try {
                ResponseObject response = (ResponseObject) in.readObject();
                if (response.getResponseStatus() == EnumResponseStatus.OK) {
                    JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
                } else {
                    JOptionPane.showMessageDialog(this, "Greska: " + response.getMessage());
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

//        try {
//            PoslovniPartnerTableModel pptm = (PoslovniPartnerTableModel) jtblNoviPartneri.getModel();
//            List<PoslovniPartner> partneri = pptm.vratiPodatke();
//            kontroler.Kontroler.sacuvajPartnere(partneri);
//            JOptionPane.showMessageDialog(this, "Partneri su sacuvani");
//        } catch (IOException ex) {
//            Logger.getLogger(FPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage());
//
//            Logger.getLogger(FPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jbtnSacuvajSveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnSacuvajSve;
    private javax.swing.JComboBox<Object> jcomboMesto;
    private javax.swing.JPanel jpnlNoviPartneri;
    private javax.swing.JPanel jpnlPoslovniPartneri;
    private javax.swing.JTable jtblNoviPartneri;
    private javax.swing.JTable jtblSviPartneri;
    private javax.swing.JTextField jtxtBroj;
    private javax.swing.JTextField jtxtMaticniBroj;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextField jtxtPib;
    private javax.swing.JTextField jtxtUlica;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboMesto() throws IOException {

        RequestObject request = new RequestObject();
        request.setAction(ActionCode.GET_ALL_PLACES);

        Socket socket = session.Session.getInstance().getSocket();
        ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
        out.writeObject(request);

        ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
        try {
            ResponseObject response = (ResponseObject) in.readObject();
            jcomboMesto.removeAllItems();
            List<Mesto> mesta = (List<Mesto>) response.getResponse();
            for (Mesto mesto : mesta) {
                jcomboMesto.addItem(mesto);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void validacija(String pib, String maticniBroj) throws Exception {
        if ((pib == null) || (pib.isEmpty())) {
            throw new Exception("Pib nije dobar");
        }
    }

    private void prikaziPartnera(PoslovniPartner pp) {
        jtxtNaziv.setText("prikazi");
    }

    private void prikaziSvePartnere() throws IOException {
//        try {
//            List<PoslovniPartner> partneri = kontroler.Kontroler.vratiPartnere();
//            TableModel pptm = new PoslovniPartnerTableModel(partneri);
//            jtblSviPartneri.setModel(pptm);
//        } catch (SQLException ex) {
//            Logger.getLogger(FPoslovniPartner.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void srediTabeluZaUnos() {
        jtblNoviPartneri.setModel(new PoslovniPartnerTableModel(new ArrayList<PoslovniPartner>()));
    }
}
