/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import klijent.NitCitanja;

/**
 *
 * @author student
 */
public class JFrameChat extends javax.swing.JFrame {
    private Socket socket;
    private PrintWriter out;
    /**
     * Creates new form JFrameChat
     */
    public JFrameChat(Socket socket) throws IOException {
        initComponents();
        this.socket=socket;
        String ime=JOptionPane.showInputDialog(this, "Unesite ime: ", "Prijavljivanje", JOptionPane.QUESTION_MESSAGE);
        out = new PrintWriter(socket.getOutputStream(),true);
        out.println(ime);
        this.setTitle(ime);
        jTextAreaporuka.grabFocus();
        NitCitanja nit = new NitCitanja(socket, jTextAreaPoruke);
        nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPoruke = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaporuka = new javax.swing.JTextArea();
        jButtonPosaljiPoruku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaPoruke.setEditable(false);
        jTextAreaPoruke.setColumns(20);
        jTextAreaPoruke.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPoruke);

        jTextAreaporuka.setColumns(20);
        jTextAreaporuka.setRows(5);
        jScrollPane2.setViewportView(jTextAreaporuka);

        jButtonPosaljiPoruku.setText("Posalji poruku");
        jButtonPosaljiPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiPorukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPosaljiPoruku, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonPosaljiPoruku, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosaljiPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiPorukuActionPerformed
        String poruka=jTextAreaporuka.getText();
        out.println(poruka);
        jTextAreaporuka.setText("");
        jTextAreaporuka.grabFocus();
    }//GEN-LAST:event_jButtonPosaljiPorukuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPosaljiPoruku;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPoruke;
    private javax.swing.JTextArea jTextAreaporuka;
    // End of variables declaration//GEN-END:variables
}
