/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Slovo;
import java.util.ArrayList;
import logika.Kontroler;
import model.ModelTabele;
import niti.NitOdbrojavanje;
import server.PokretanjeServera;

/**
 *
 * @author Miroslav
 */
public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelZaNestane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtZadataRec = new javax.swing.JTextField();
        btnUnesi = new javax.swing.JButton();
        labelaZadataRec = new javax.swing.JLabel();
        labelaUkupnoVreme = new javax.swing.JLabel();
        labelaTajmer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSlova = new javax.swing.JTable();
        labelaImePrvog = new javax.swing.JLabel();
        labelaImeDrugog = new javax.swing.JLabel();
        labelaPoeniPrvog = new javax.swing.JLabel();
        labelaPoeniDrugog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rec");

        btnUnesi.setText("Unesi rec");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelZaNestaneLayout = new javax.swing.GroupLayout(panelZaNestane);
        panelZaNestane.setLayout(panelZaNestaneLayout);
        panelZaNestaneLayout.setHorizontalGroup(
            panelZaNestaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtZadataRec, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnUnesi)
                .addContainerGap())
        );
        panelZaNestaneLayout.setVerticalGroup(
            panelZaNestaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZaNestaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelZaNestaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtZadataRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnesi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelaZadataRec.setText("jLabel2");

        labelaUkupnoVreme.setText("jLabel2");

        labelaTajmer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelaTajmer.setText("jLabel3");

        tabelaSlova.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaSlova);

        labelaImePrvog.setText("jLabel2");

        labelaImeDrugog.setText("jLabel2");

        labelaPoeniPrvog.setText("jLabel2");

        labelaPoeniDrugog.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelaUkupnoVreme)
                            .addComponent(labelaTajmer))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelaImeDrugog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelaPoeniDrugog))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelaImePrvog)
                                .addGap(30, 30, 30)
                                .addComponent(labelaPoeniPrvog)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panelZaNestane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelaZadataRec)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelZaNestane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelaZadataRec)
                .addGap(7, 7, 7)
                .addComponent(labelaUkupnoVreme)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelaTajmer)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelaImePrvog)
                            .addComponent(labelaPoeniPrvog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelaImeDrugog)
                            .addComponent(labelaPoeniDrugog)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        String rec = txtZadataRec.getText().toUpperCase();
         labelaZadataRec.setText("ZADATA REC: "+rec);
         PokretanjeServera ps = new PokretanjeServera(this);
         ps.start();
         
         ArrayList<Slovo> listaSlova = new ArrayList<>();
         
         for (int i = 0; i < rec.length(); i++) {
            char slovo1 = rec.charAt(i);
            int brojac = 1;
             for (int j = i+1; j < rec.length(); j++) {
                 char slovo2 = rec.charAt(j);
                 if(slovo1 == slovo2){
                     brojac++;
                 }
                 
             }
             
             Slovo s = new Slovo(slovo1+"", brojac);
             if(!listaSlova.contains(s)){
                 listaSlova.add(s);
             }
            
             Kontroler.getInstance().setListaslova(listaSlova);
        }
         
         
        panelZaNestane.setVisible(false);
        
        int ukupnoSekundi = listaSlova.size() * 3;
        Kontroler.getInstance().setUkupanBrojSekundi(ukupnoSekundi);
        labelaUkupnoVreme.setText("Ukupnos sekundi "+ukupnoSekundi + "");
        labelaTajmer.setText(ukupnoSekundi + "");
        
        
        
    }//GEN-LAST:event_btnUnesiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelaImeDrugog;
    private javax.swing.JLabel labelaImePrvog;
    private javax.swing.JLabel labelaPoeniDrugog;
    private javax.swing.JLabel labelaPoeniPrvog;
    private javax.swing.JLabel labelaTajmer;
    private javax.swing.JLabel labelaUkupnoVreme;
    private javax.swing.JLabel labelaZadataRec;
    private javax.swing.JPanel panelZaNestane;
    private javax.swing.JTable tabelaSlova;
    private javax.swing.JTextField txtZadataRec;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabele mt = new ModelTabele();
        tabelaSlova.setModel(mt);
    }

    public void namestiTajmer(int brojSekundi) {
        labelaTajmer.setText(brojSekundi+"");
    }

    public void promeniRezultat() {

        labelaImeDrugog.setText(Kontroler.getInstance().getImeDrugog());
        labelaImePrvog.setText(Kontroler.getInstance().getImePrvog());
        labelaPoeniDrugog.setText(Kontroler.getInstance().getBrojPoenaDrugog()+"");
        labelaPoeniPrvog.setText(Kontroler.getInstance().getBrojPoenaPrvog()+"");
    }
}
