/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import javax.swing.JOptionPane;
import nit.NitBingo;
import nit.NitSat;

/**
 *
 * @author student
 */
public class FBingo extends javax.swing.JFrame {

    NitBingo nitBingo;

    /**
     * Creates new form FBingo
     */
    public FBingo() {
        initComponents();
        pokreniSat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtBr1 = new javax.swing.JTextField();
        jTxtBr2 = new javax.swing.JTextField();
        jTxtBr3 = new javax.swing.JTextField();
        jBtnPokreni = new javax.swing.JButton();
        jBtnZaustavi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtSat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnPokreni.setText("Pokreni");
        jBtnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPokreniActionPerformed(evt);
            }
        });

        jBtnZaustavi.setText("Zaustavi");
        jBtnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZaustaviActionPerformed(evt);
            }
        });

        jLabel1.setText("Sat:");

        jTxtSat.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxtSat.setText("10:22:30");
        jTxtSat.setEnabled(false);
        jTxtSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnPokreni)
                            .addComponent(jTxtBr1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jTxtBr2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTxtBr3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnZaustavi)
                                .addGap(107, 107, 107))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPokreni)
                    .addComponent(jBtnZaustavi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSatActionPerformed

    private void jBtnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPokreniActionPerformed
        // TODO add your handling code here:
        /*while (true) {
            double br1 = Math.random();
            int broj1 = (int) (br1 * 10);
            jTxtBr1.setText(broj1 + "");

            double br2 = Math.random();
            int broj2 = (int) (br2 * 10);
            jTxtBr2.setText(broj2 + "");

            double br3 = Math.random();
            int broj3 = (int) (br3 * 10);
            jTxtBr3.setText(broj3 + "");
        }*/
        if (nitBingo == null || !nitBingo.isAlive()) {
            nitBingo = new NitBingo(jTxtBr1, jTxtBr2, jTxtBr3);
            nitBingo.start();
        } else{
            JOptionPane.showMessageDialog(this, "Bingo se vrti");
        }
    }//GEN-LAST:event_jBtnPokreniActionPerformed

    private void jBtnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZaustaviActionPerformed
        // TODO add your handling code here:
        if (nitBingo != null) {
            nitBingo.interrupt();
        }
    }//GEN-LAST:event_jBtnZaustaviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPokreni;
    private javax.swing.JButton jBtnZaustavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtBr1;
    private javax.swing.JTextField jTxtBr2;
    private javax.swing.JTextField jTxtBr3;
    private javax.swing.JTextField jTxtSat;
    // End of variables declaration//GEN-END:variables

    private void pokreniSat() {
        nit.NitSat n = new NitSat(jTxtSat);
    }
}
