/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import nit.NitSat;

/**
 *
 * @author student
 */
public class FSat extends javax.swing.JFrame {

    /**
     * Creates new form FSat
     */
    public FSat() {
        initComponents();
        
        //prikaziSat();
    }

    public void prikaziSat(){
       /* while (true) {
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
            String vreme = sdf.format(date);
            jTxtSat.setText(vreme);
        }
    */
       nit.NitSat n= new NitSat(jTxtSat);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtSat = new javax.swing.JTextField();
        jBtnPoruka = new javax.swing.JButton();
        jBtnBingo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sat:");

        jTxtSat.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTxtSat.setText("10:22:30");
        jTxtSat.setEnabled(false);
        jTxtSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSatActionPerformed(evt);
            }
        });

        jBtnPoruka.setText("Prikazi poruku");
        jBtnPoruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPorukaActionPerformed(evt);
            }
        });

        jBtnBingo.setText("Prikazi Bingo");
        jBtnBingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBingoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnBingo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPoruka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jBtnPoruka)))
                .addGap(26, 26, 26)
                .addComponent(jBtnBingo)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSatActionPerformed

    private void jBtnPorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPorukaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Poruka");
    }//GEN-LAST:event_jBtnPorukaActionPerformed

    private void jBtnBingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBingoActionPerformed
        // TODO add your handling code here:
        FBingo fb= new FBingo();
        fb.setVisible(true);
                
    }//GEN-LAST:event_jBtnBingoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBingo;
    private javax.swing.JButton jBtnPoruka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtSat;
    // End of variables declaration//GEN-END:variables
}
